# Generated by Django 3.1.3 on 2020-11-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
