# Generated by Django 3.1.3 on 2020-11-22 03:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_empleado_habilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='habilidad',
            new_name='habilidades',
        ),
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
